// Code generated by entc, DO NOT EDIT.

package app

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppKey holds the string denoting the app_key field in the database.
	FieldAppKey = "app_key"
	// FieldAppScreen holds the string denoting the app_screen field in the database.
	FieldAppScreen = "app_screen"
	// FieldAppStatus holds the string denoting the app_status field in the database.
	FieldAppStatus = "app_status"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"

	// Table holds the table name of the app in the database.
	Table = "apps"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldAppKey,
	FieldAppScreen,
	FieldAppStatus,
	FieldCreateTime,
	FieldDeleteTime,
	FieldUpdateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAppScreen holds the default value on creation for the "app_screen" field.
	DefaultAppScreen string
	// DefaultAppStatus holds the default value on creation for the "app_status" field.
	DefaultAppStatus int8
)
