// Code generated by entc, DO NOT EDIT.

package ent

import (
	"pvp/internal/data/ent/app"
	"pvp/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescAppScreen is the schema descriptor for app_screen field.
	appDescAppScreen := appFields[1].Descriptor()
	// app.DefaultAppScreen holds the default value on creation for the app_screen field.
	app.DefaultAppScreen = appDescAppScreen.Default.(string)
	// appDescAppStatus is the schema descriptor for app_status field.
	appDescAppStatus := appFields[2].Descriptor()
	// app.DefaultAppStatus holds the default value on creation for the app_status field.
	app.DefaultAppStatus = appDescAppStatus.Default.(int8)
}
